skins.2=2
name.2=iregex:XaPhobia

skins.3=3
name.3=iregex:Programmer Art

skins.4=4
name.4=iregex:Jappa

skins.5=2 3 4
weights.5=3 3 3


https://modrinth.com/resourcepack/zombie-pigman-replaces-zombified-piglin/gallery