skins.2=2
name.2=iregex:Classic Beard

skins.4=4
name.4=iregex:Classic No Beard

skins.6=6
name.6=iregex:Tuxedo Beard

skins.8=8
name.8=iregex:Tuxedo No Beard

skins.10=10
name.10=iregex:Athlete Beard

skins.12=12
name.12=iregex:Athlete No Beard

skins.14=14
name.14=iregex:Prison Beard

skins.16=16
name.16=iregex:Prison No Beard

skins.22=22
name.22=iregex:Boxer Beard

skins.24=24
name.24=iregex:Boxer No Beard

skins.25= 2 4 6 8 10 12 14 16 22 24
weights.25=1 1 1 1 1 1 1 1 1 1
